// flow-typed signature: 6b5ce94e9373396dccaea76561664ab3
// flow-typed version: <<STUB>>/react-conflux_v^0.0.2-beta.6/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-conflux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-conflux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-conflux/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-conflux/dist/cjs.min' {
  declare module.exports: any;
}

declare module 'react-conflux/dist/esm' {
  declare module.exports: any;
}

declare module 'react-conflux/dist/esm.min' {
  declare module.exports: any;
}

declare module 'react-conflux/dist/umd' {
  declare module.exports: any;
}

declare module 'react-conflux/dist/umd.min' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src/App' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src/components/Counter' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src/store/constants' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src/store/contexts' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src/store/reducers/counterReducer' {
  declare module.exports: any;
}

declare module 'react-conflux/examples/counter/src/store/reducers/titleReducer' {
  declare module.exports: any;
}

declare module 'react-conflux/rollup.config' {
  declare module.exports: any;
}

declare module 'react-conflux/src/hooks' {
  declare module.exports: any;
}

declare module 'react-conflux/src/hooks/useStateValue' {
  declare module.exports: any;
}

declare module 'react-conflux/src' {
  declare module.exports: any;
}

declare module 'react-conflux/src/store' {
  declare module.exports: any;
}

declare module 'react-conflux/src/store/StateProvider' {
  declare module.exports: any;
}

declare module 'react-conflux/test/helpers/components' {
  declare module.exports: any;
}

declare module 'react-conflux/test/helpers/constants' {
  declare module.exports: any;
}

declare module 'react-conflux/test/helpers/contexts' {
  declare module.exports: any;
}

declare module 'react-conflux/test/helpers/reducers' {
  declare module.exports: any;
}

declare module 'react-conflux/test/StateProvider.test' {
  declare module.exports: any;
}

declare module 'react-conflux/test/useStateValue.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-conflux/dist/cjs.js' {
  declare module.exports: $Exports<'react-conflux/dist/cjs'>;
}
declare module 'react-conflux/dist/cjs.min.js' {
  declare module.exports: $Exports<'react-conflux/dist/cjs.min'>;
}
declare module 'react-conflux/dist/esm.js' {
  declare module.exports: $Exports<'react-conflux/dist/esm'>;
}
declare module 'react-conflux/dist/esm.min.js' {
  declare module.exports: $Exports<'react-conflux/dist/esm.min'>;
}
declare module 'react-conflux/dist/umd.js' {
  declare module.exports: $Exports<'react-conflux/dist/umd'>;
}
declare module 'react-conflux/dist/umd.min.js' {
  declare module.exports: $Exports<'react-conflux/dist/umd.min'>;
}
declare module 'react-conflux/examples/counter/src/App.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src/App'>;
}
declare module 'react-conflux/examples/counter/src/components/Counter.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src/components/Counter'>;
}
declare module 'react-conflux/examples/counter/src/index' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src'>;
}
declare module 'react-conflux/examples/counter/src/index.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src'>;
}
declare module 'react-conflux/examples/counter/src/store/constants.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src/store/constants'>;
}
declare module 'react-conflux/examples/counter/src/store/contexts.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src/store/contexts'>;
}
declare module 'react-conflux/examples/counter/src/store/reducers/counterReducer.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src/store/reducers/counterReducer'>;
}
declare module 'react-conflux/examples/counter/src/store/reducers/titleReducer.js' {
  declare module.exports: $Exports<'react-conflux/examples/counter/src/store/reducers/titleReducer'>;
}
declare module 'react-conflux/index' {
  declare module.exports: $Exports<'react-conflux'>;
}
declare module 'react-conflux/index.js' {
  declare module.exports: $Exports<'react-conflux'>;
}
declare module 'react-conflux/rollup.config.js' {
  declare module.exports: $Exports<'react-conflux/rollup.config'>;
}
declare module 'react-conflux/src/hooks/index' {
  declare module.exports: $Exports<'react-conflux/src/hooks'>;
}
declare module 'react-conflux/src/hooks/index.js' {
  declare module.exports: $Exports<'react-conflux/src/hooks'>;
}
declare module 'react-conflux/src/hooks/useStateValue.js' {
  declare module.exports: $Exports<'react-conflux/src/hooks/useStateValue'>;
}
declare module 'react-conflux/src/index' {
  declare module.exports: $Exports<'react-conflux/src'>;
}
declare module 'react-conflux/src/index.js' {
  declare module.exports: $Exports<'react-conflux/src'>;
}
declare module 'react-conflux/src/store/index' {
  declare module.exports: $Exports<'react-conflux/src/store'>;
}
declare module 'react-conflux/src/store/index.js' {
  declare module.exports: $Exports<'react-conflux/src/store'>;
}
declare module 'react-conflux/src/store/StateProvider.jsx' {
  declare module.exports: $Exports<'react-conflux/src/store/StateProvider'>;
}
declare module 'react-conflux/test/helpers/components.js' {
  declare module.exports: $Exports<'react-conflux/test/helpers/components'>;
}
declare module 'react-conflux/test/helpers/constants.js' {
  declare module.exports: $Exports<'react-conflux/test/helpers/constants'>;
}
declare module 'react-conflux/test/helpers/contexts.js' {
  declare module.exports: $Exports<'react-conflux/test/helpers/contexts'>;
}
declare module 'react-conflux/test/helpers/reducers.js' {
  declare module.exports: $Exports<'react-conflux/test/helpers/reducers'>;
}
declare module 'react-conflux/test/StateProvider.test.js' {
  declare module.exports: $Exports<'react-conflux/test/StateProvider.test'>;
}
declare module 'react-conflux/test/useStateValue.test.js' {
  declare module.exports: $Exports<'react-conflux/test/useStateValue.test'>;
}
